<?php /** @var $block \Magento\Framework\View\Element\Template */ ?>
<?php /** refer landing-separate.phtml for each CSS file */?>
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/landing/klevu-landing-merge.css'); ?>" />

<?php /** Price slider library */?>
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::lib/nouislider.min.css'); ?>" />
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::lib/nouislider.js') ?>"></script>

<?php /** Refer landing-separate.phtml for each JS file */?>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing-merge.js') ?>"></script>
