<?php /** @var $block \Magento\Framework\View\Element\Template */ ?>

<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/landing/klevu-landing.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/landing/klevu-landing-responsive.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/landing/klevu-landing-add-to-cart.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/klevu-facets.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/landing/klevu-landing-filter-left.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/landing/klevu-landing-mobile-sliding-filter.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/landing/klevu-landing-product-quick-view.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/landing/klevu-landing-color-swatches.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/landing/klevu-landing-custom-pagination.css'); ?>" />
<?php /*<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/landing/klevu-landing-filter-top.css'); ?>" /> */?>
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/landing/klevu-landing-product-VAT-label.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/landing/klevu-landing-tab-results.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/landing/klevu-landing-product-stock-label.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/landing/klevu-landing-product-badge.css'); ?>" />

<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::lib/nouislider.min.css'); ?>" />


<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::lib/nouislider.js') ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing.js') ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing-init.js') ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing-sort.js') ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing-limit.js') ?>"></script>

<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/klevu-analytics-utils.js') ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing-add-to-cart.js') ?>"></script>

<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing-tab-results.js') ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing-product-stock-label.js') ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing-product-badge.js') ?>"></script>

<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing-magento-image-path-update.js') ?>"></script>

<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing-filter-price-slider.js') ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing-mobile-sliding-filter.js') ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing-custom-pagination.js') ?>"></script>
<?php /* <script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing-filter-top.js') ?>"></script> */?>

<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/klevu-facets.js') ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing-filter-left.js') ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing-product-quick-view.js') ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing-color-swatches.js') ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing-product-VAT-label.js') ?>"></script>

