<?php /** @var $block \Magento\Framework\View\Element\Template */ ?>
<?php /** Refer quick-separate.phtml for each CSS file */?>
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/quick/klevu-quick-merge.css'); ?>" />
<script type="text/javascript" src="//js.klevu.com/klevu-js-v2/2.0/klevu.js"></script>
<?php /** Refer quick-separate.phtml for each JS file */?>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/quick/klevu-quick-merge.js') ?>"></script>
