<?php /** @var $block \Magento\Framework\View\Element\Template */ ?>

<script type="text/javascript" src="//js.klevu.com/klevu-js-v2/2.0/klevu.js"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/klevu-settings.js'); ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/quick/klevu-quick.js'); ?>"></script>

<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/klevu-add-to-cart.js'); ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/quick/klevu-quick-add-to-cart.js'); ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/quick/klevu-quick-trending-products.js'); ?>"></script>

<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/klevu-product-data-modification.js'); ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/klevu-product-recommendation.js'); ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/quick/klevu-quick-magento-image-path-update.js'); ?>"></script>

<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/quick/klevu-quick.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/quick/klevu-quick-add-to-cart.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/quick/klevu-quick-view-color-swatches.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/klevu-additional-changes.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/klevu-facets.css'); ?>" />

<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/klevu-analytics-utils.js') ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/klevu-color-swatches.js') ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/quick/klevu-quick-view-color-swatches.js') ?>"></script>
