<?php /** @var $block \Magento\Framework\View\Element\Template */ ?>

<script type="text/javascript" src="//js.klevu.com/klevu-js-v2/2.0/klevu.js"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/klevu-settings.js'); ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/quick/klevu-quick.js'); ?>"></script>

<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/klevu-add-to-cart.js'); ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/quick/klevu-quick-add-to-cart.js'); ?>"></script>

<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/quick/klevu-quick.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/quick/klevu-quick-add-to-cart.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/quick/klevu-quick-view-color-swatches.css'); ?>" />

<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/klevu-analytics-utils.js') ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/klevu-color-swatches.js') ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/quick/klevu-quick-view-color-swatches.js') ?>"></script>
