<script type="template/klevu" id="klevuQuickProductBlock">
    <li class="klevuProduct" data-id="<%=dataLocal.id%>">
        <%=helper.render('quickSearchProductAddToCart',scope,data,dataLocal) %>
        <a target="_self" href="<%=dataLocal.url%>" data-id="<%=dataLocal.id%>"  class="klevuQuickProductInnerBlock trackProductClick">
            <div class="klevuProductItemTop">
                <div class="klevuQuickImgWrap">
                    <div class="klevuQuickDiscountBadge"><strong><%=dataLocal.stickyLabelHead%></strong></div>
                    <img src="<%=dataLocal.image%>" alt="<%=dataLocal.name%>" />
                </div>
            </div>
            <div class="klevuProductItemBottom">
                <div class="klevuQuickProductDescBlock">
                    <div class="klevuQuickProductName"><%=dataLocal.name%></div>
                    <div class="klevuQuickProductDesc">
                        <div class="klevuSpectxt"><%=dataLocal.summaryAttribute%><span><%=dataLocal.stickyLabelText%></span></div>
                    </div>
                    <div class="klevuQuickProductPrice">
                        <% if(dataLocal.ondiscount && dataLocal.ondiscount == "true") { %>
                            <% if(dataLocal.salePrice ) { %>
                                <span class="klevuQuickSalePrice klevuQuickSpecialPrice">
                                    <%=helper.processCurrency(dataLocal.currency,parseFloat(dataLocal.salePrice))%>
                                </span>
                            <% } %>
                            <% if(dataLocal.price) { %>
                                <span class="klevuQuickOrigPrice"><%=helper.translate("Original price %s",helper.processCurrency(dataLocal.currency,parseFloat(dataLocal.price)))%></span>
                            <% } %>
                        <% } else { %>
                            <% if(dataLocal.salePrice ) { %>
                                <span class="klevuQuickSalePrice">
                                    <span class="klevuQuickPriceGreyText"></span>
                                    <%=helper.processCurrency(dataLocal.currency,parseFloat(dataLocal.salePrice))%>
                                </span>
                            <% } %>
                        <% } %>
                    </div>
                </div>
            </div>
            <div class="klevuClearLeft"></div>
        </a>
    </li>
</script>

<script type="template/klevu" id="quickSearchProductAddToCart">
    <div class="klevuQuickAddtoCart" data-id="<%=dataLocal.id%>" >
        <button class="klevuQuickCartBtn">Add to Cart</button>
    </div>
</script>


<script type="template/klevu" id="quickViewProductSwatch">
    <% var swatchesInfoList = dataLocal.swatchesInfo; var quickViewSwatchIndex = 1; %>
    <% if(swatchesInfoList && swatchesInfoList.length){ %>
    <div class="productQuick-colorInStock">
        <span class="productQuick-label"><%=helper.translate("Color Variants:") %></span>
        <div class="kuSwatches">
            <% helper.each(swatchesInfoList,function(key,item){ if(quickViewSwatchIndex > 3){ return true;} %>
            <div class="kuSwatchItem"> <a target="_self" href="javascript:void(0)" data-variant="<%=item.variantId%>" class="kuSwatchLink klevuSwatchColorGrid" title="<%=item.variantColor%>" style="background-color:<%=item.variantColor%>"></a></div>
            <% quickViewSwatchIndex++; });%>
            <% if(swatchesInfoList.length > 3){ %>
            <div class="kuSwatchItem kuSwatchMore">
                <a target="_self" href="<%=dataLocal.url%>" class="kuSwatchLink">
                            <span class="kuSwatchMoreText">
                                +<%=(swatchesInfoList.length-3)%>
                            </span>
                </a>
            </div>
            <% } %>
        </div>
    </div>
    <% } %>
</script>
